htables French translation.
py-libhdate/py-libhdate pull request #103
Opened 2022-10-18 20:18 UTC by DanBendavid

# Description

# Closes issue(s)

  Fixes: #<issue number>

# Changes included (select only one)

- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [x] Breaking change (change that is not backwards-compatible)

# Checklist

- [ ] Code passes tox

2022-10-18 20:19 UTC, DanBendavid commented
htables with one addional language but the lib is not fixed

2022-10-24 13:50 UTC, tsvi requested changes
Looks good, please add a commit returning the empty lines, and I'll commit.
I hope to add support for multiple languages soon.

Thank you very much

2022-10-24 13:50 UTC, tsvi commented on hdate/htables.py
> -
Here as well

2022-10-25 15:07 UTC, tmostovi approved these changes

2022-10-25 15:09 UTC, merged