Add support for night according to Rabenou Tam and mincha gedola according to 30 min
py-libhdate/py-libhdate pull request #142
Opened 2024-11-14 13:19 UTC by DanBendavid

# Description
Adding Night by Rabenou Time in the Zmanim
	
modified:   hdate/zmanim.py
modified:   hdate/htables.py
modified:   tests/test_hdate_api.py
        

# Closes issue(s)

  Fixes: #<issue number>

# Changes included (select only one)

- [ ] Bugfix (non-breaking change that solves an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible)

# Checklist

- [ ] Code passes tox

2024-11-14 15:14 UTC, tsvi commented
Much better.
Please do not change mincha gedola, rather add the other shita.
The current calculation is in accordance with mishna brura in שער הציון רל"ג ח'
![image](https://github.com/user-attachments/assets/93337ace-7dca-450e-a32f-f8e10f763083)

But we should support other calculations as well. Let's call it big_mincha_30_min

2024-11-14 15:15 UTC, tsvi commented
Also you're failing black formatting:
`pdm run black` (Should not happen if you have pre-commit installed)

2024-11-15 00:46 UTC, tsvi requested changes

2024-11-15 00:46 UTC, tsvi commented on README.rst
> +    מנחה גדולה ל - 13:10:00
Much better, please change in Hebrew to 
מנחה גדולה 30 דק

The current wording is not clear.
After that I will merge this PR.

2024-11-15 11:13 UTC, DanBendavid commented
I will work on multilanguage this sunday. . 
What do you recommend ? Cause moving from hebrew=true to lang=hebrew is going to be a breaking change.

2024-11-16 18:14 UTC, tsvi approved these changes
Looks good.
Thank you and kol hakavod.

2024-11-16 18:14 UTC, merged

2024-11-16 18:15 UTC, tsvi commented
> I will work on multilanguage this sunday. . What do you recommend ? Cause moving from hebrew=true to lang=hebrew is going to be a breaking change.

It's ok to have a breaking change. I think it's a good idea. Let's change it from hebrew to language.
The internal implementation we can change later.